name: "Pull Request Docs Check"
on: [pull_request, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
      # https://docs.github.com/en/actions/guides/building-and-testing-python#caching-dependencies
      # ^-- How to set up caching for pip on Ubuntu
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    # https://docs.github.com/en/actions/guides/building-and-testing-python#installing-dependencies
    # ^-- This gives info on installing dependencies with pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Debugging information
      run: |
        echo "github.ref:" ${{github.ref}}
        echo "github.event_name:" ${{github.event_name}}
        echo "github.head_ref:" ${{github.head_ref}}
        echo "github.base_ref:" ${{github.base_ref}}
        git rev-parse --abbrev-ref HEAD
        git branch
        git branch -a
        git remote -v
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: Build Sphinx docs
      run: |
          make dirhtml
          
      # Deploy
      # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _gh-pages/
        force_orphan: true
